language: node_js
node_js: "10.15"
cache: yarn

stages:
  - name: test
  - name: deploy
    if: tag is present

jobs:
  include:
    - stage: test
    - stage: deploy
      name: Deploy Package
      script: scripts/deploy.js
