version: '3.7'

x-node-defaults: &node
  tty: true
  init: true
  image: node:10.15
  entrypoint: ["node"]
  working_dir: /root
  volumes:
    - .:/root:cached
    - ./node_modules:/root/node_modules:delegated
    - yarn-cache:/.yarn-cache

x-env-defaults: &env
  YARN_CACHE_FOLDER: /.yarn-cache
  NODE_ENV: development

services:
  app:
    <<: *node
    entrypoint: ["node_modules/.bin/gulp"]
    environment:
      <<: *env
      PORT: 80
      EXPOSED_PORT: 4987
    ports:
      - "4987:80"

  terminal:
    <<: *node
    entrypoint: ["/bin/bash"]
    environment:
      <<: *env

  yarn:
    <<: *node
    entrypoint: ["yarn"]
    environment:
      <<: *env

  lint:
    <<: *node
    entrypoint: ["yarn"]
    command: ["run", "lint"]
    environment:
      <<: *env

volumes:
  yarn-cache: {}
